### ISSUE TITLE
Script should follow user talk page redirects

### ISSUE THREAD

**Issue by bardiharborow** [wikimedia-gadgets/afc-helper#90] opened 2018-02-03 07:08 UTC
The script should not have made [this edit](https://en.wikipedia.org/wiki/Special:Diff/823759466), but instead should have followed the talk page redirect and left a message at the redirect target.

**Comment by enterprisey** [comment] 2021-01-18 09:31
To reproduce: comment on a draft, with the "Notify user" option enabled, submitted by a user whose talk page is a redirect. Currently, the script will send a notice to the redirect, not the target of the redirect.

I'm pretty confident that all we need to do is add the parameter `redirect: "true"` to the API call that we use to notify users. The function that notifies users is notifyUsers in core.js, which uses editPage in core.js. While we could solve this by adding `redirect: "true"` to the request in editPage, that'll probably mess up other things. So, we should add a way for the callers of editPage to ask it to set `redirect: "true"`, perhaps by handling `options.followRedirect` (to use a more obvious name than just "redirect").

**Comment by primefac** [comment] 2021-01-18 10:43
As a note, Twinkle has [the same issue](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_43#Twinkle_should_check_talk_page_for_redirects_before_adding_templates) so if this one gets solved it might be good to let Amory know so that it can be fixed in both locations.

**Comment by puneetdwivedi** [comment] 2021-02-10 18:50
i want to work on this. how i can start

**Comment by enterprisey** [comment] 2021-02-15 00:47
@puneetdwivedi Sorry! Not sure how I missed this. Here are [instructions on getting set up](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Helper_script/Contributing); if you run into any trouble, post here or on the [other help venues](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Helper_script/Contributing#Need_help?).

**Comment by enterprisey** [comment] 2021-02-25 09:17
@puneetdwivedi How is this issue going? Please let me know if you've run into any problems.

**Comment by Ankur21980** [comment] 2021-03-19 18:11
Hello! @enterprisey, I would like to work on this issue. Is it open yet?

**Comment by enterprisey** [comment] 2021-03-20 08:51
@Ankur21980 hi! I would like to not assign this issue to someone else just yet - if you really want to work on this issue, please wait until the person currently assigned has not responded for another week. Alternatively, please ping me in a new topic in [our Zulip channel](https://wikimedia.zulipchat.com/#narrow/stream/273783-enwiki-afch) - there are more issues that do not have the good-first-issue tag that might be easy to work on, depending on your level of experience.

@puneetdwivedi - are you still available to work on this issue? Unfortunately easy issues on this repository are not that easy to find, so please let me know whether or not you plan to continue working on this issue. If you do not make a comment on this issue with your status by a week from now (the 27th of March) I will assume you are not available, and will mark  this issue as open for anyone to take.

**Comment by Prernajha2609** [comment] 2022-01-16 07:10
hello @enterprisey, I would like to contribute to this project, I will need a little guidance to start.

**Comment by enterprisey** [comment] 2022-01-16 07:13
@Prernajha2609 sure. Follow https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Articles_for_creation/Helper_script/Contributing/Developer_setup and let me know if you get stuck.

**Comment by Prernajha2609** [comment] 2022-01-16 08:44
how should I start after setting up the environment?

**Comment by NovemLinguae** [comment] 2022-01-16 10:52
I imagine you'd want to pick an easy issue from the [list of issues](https://github.com/WPAFC/afch-rewrite/issues), write a patch, test it using https://test.wikipedia.org/, then [submit a pull request](https://www.google.com/search?q=how+to+submit+a+pull+request+on+github).

**Comment by Prernajha2609** [comment] 2022-01-16 19:47
Hey, can you suggest to me some beginner-friendly issues to work on?

**Comment by NovemLinguae** [comment] 2022-05-13 11:31
Mentioned today by Mathglot at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Bug_in_AFCH_for_renamed_users

**Comment by primefac** [comment] 2022-05-13 11:34
Is #99 a duplicate of this issue?

**Comment by NovemLinguae** [comment] 2024-01-27 00:38
Mentioned today by Star Mississippi at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Script_question%2Fbug%3F

**Comment by NovemLinguae** [comment] 2024-04-24 04:19
Will spin the bug out into its own ticket. #349

**Closed by NovemLinguae** 2024-04-24 04:19 UTC
Labels: C-bug, E-good-first-issue, frequently-requested
