### ISSUE TITLE
AfCH script not working

### ISSUE THREAD

**Issue by ghost** [wikimedia-gadgets/afc-helper#71] opened 2015-12-17 22:44 UTC
After selecting "Review (AFCH)" from the dropdown menu, the traditional three-button window appears but none of the buttons or links react when clicked. (So "Accept", "Decline", "Comment", "Clean submission" and "Mark as under review" aren't working.)

Let me know if more information is needed.

**Comment by hasteur** [comment] 2015-12-17 22:46
Were there any errors on the JS console? What page were you trying to
review?

**Comment by josve05a** [comment] 2015-12-17 22:50
On all drafts.
![screenshot 2015-12-17 at 23 50 07](https://cloud.githubusercontent.com/assets/7117013/11884286/eb8fce0c-a518-11e5-9c2b-17302101f941.png)

```javascript
Uncaught TypeError: Cannot read property 'get' of undefinedMwMessagePosterFactory.create @ VM124:34
MwFeedback @ VM124:35
$.extend.initFeedback @ VM123:778
(anonymous function) @ VM152:821
(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:47
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:48
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
deferred.(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:47
(anonymous function) @ VM152:73
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
deferred.(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:47
(anonymous function) @ VM123:931
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
deferred.(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:47
(anonymous function) @ VM123:850
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
deferred.(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:47
(anonymous function) @ VM123:1119
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
deferred.(anonymous function) @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:47
(anonymous function) @ VM93:3
fire @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:45
self.fireWith @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:46
done @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:135
callback @ load.php?debug=false&lang=en&modules=jquery%2Cmediawiki&only=scripts&skin=vector&version=%2Ba17lhsh:141
```

**Comment by hasteur** [comment] 2015-12-17 23:00
The buttons fail because the JavaScript croaked while loading. I'm mobile
right now so cant see if this is localized to you or if this is widespread.

**Comment by josve05a** [comment] 2015-12-17 23:02
It is confirmed on IRC that this is widespread for everyone. Using beta as a fallback as of right now.

**Comment by theopolisme** [comment] 2015-12-17 23:13
Looking...

**Comment by theopolisme** [comment] 2015-12-17 23:21
I've implemented a temporary fix and pushed it to enwiki. Please try clearing your cache and do comment here if the issue continues.

Leaving this issue open until I figure out what went wrong with mwFeedback...

**Comment by theopolisme** [comment] 2015-12-17 23:28
On enwiki: https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/Helper_script#Draft:_Dixien_LLC

**Comment by NovemLinguae** [comment] 2024-04-25 11:50
This code has been commented out for 9 years. I plan to delete it as dead code in patch #351. Closing.

**Closed by NovemLinguae** 2024-04-25 11:50 UTC
Labels: C-bug
