### ISSUE TITLE
Overwriting another reviewer's AFC accept/decline/comment (edit conflict avoidance)

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afc-helper#153] opened 2021-03-02 22:58 UTC
I had this happen today. It is possible to overwrite somebody else's AFC decline, if they finalize their decline while you're writing yours.

Possible solution: When the reviewer presses the decline button, have AFCH check the page history, and if there have been any edits within the last 10 minutes, give the reviewer a warning when submitting.

Possible solution # 2: When AFCH loads, save the current time. When the reviewer presses the decline button, have AFCH check the page history, and if there have been any edits since the saved time, notify the submitter of an edit conflict.

edit: Looks like it can happen with comments, too. And with one person accepting, one person commenting. So any combination of types is probably possible.

https://en.wikipedia.org/w/index.php?title=Draft:Jointed_Boiler_Locomotive&type=revision&diff=1009914671&oldid=1009913368&diffmode=source

**Comment by NovemLinguae** [comment] 2021-03-24 07:47
Happened again to me just now. Here's an example.

https://en.wikipedia.org/w/index.php?title=Draft:Dhanusha_Murugasan&type=revision&diff=1013933947&oldid=1013933811&diffmode=source

**Comment by primefac** [comment] 2021-03-24 13:11
This is a duplicate of #116

**Comment by Dreamy-Jazz** [comment] 2021-07-29 15:53
With the latest AfC drive I've seen three editors edit conflict to review a draft and the script overwrite each in turn.

**Comment by siddharthvp** [comment] 2022-03-29 04:33
What I would suggest is to check for new edits being made to the page every 5 or 10 seconds. If new changes are detected, show a notice saying "**This draft has been recently edited N times by USERNAME. Reload to see the latest changes**". Ideally, any half-written comment in the text box should be preserved across the reload.

The API call to do this is very cheap since we just have to fetch the metadata of _newer_ revisions – not the content, and this will be empty most of the time.

Checking for conflict only when the user is actually accepting/declining wastes their time as they need not have done that if someone had already done so in the interim. This also handles the case of commenting conflicts.

**Closed** 2024-04-23 08:08 UTC
Labels: C-bug, frequently-requested
