### ISSUE TITLE
Move Over Redirect

### ISSUE THREAD

**Issue by djkees** [wikimedia-gadgets/afc-helper#93] opened 2018-04-29 02:36 UTC
Related discussion: https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Reducing_backlog

Right now non-admins cannot move drafts over redirects.

It would be useful if the incoming link is a redirect, the script would G6 the incoming link and tag the draft with {{db-move}}.

**Comment by NovemLinguae** [comment] 2023-11-30 02:02
Closing as duplicate of https://github.com/wikimedia-gadgets/afc-helper/issues/243

**Closed by NovemLinguae** 2023-11-30 02:02 UTC
Labels: C-enhancement
